# Generated by Django 4.1.4 on 2023-05-22 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_No',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
