# Generated by Django 4.1.4 on 2023-05-24 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_avatar_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar_url',
        ),
    ]
