# Generated by Django 4.1.4 on 2023-05-23 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='productimage')),
                ('product_image_url', models.URLField(blank=True, null=True)),
                ('price', models.PositiveIntegerField()),
                ('discription', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_ctg', to='product.category')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
