# Generated by Django 4.1.4 on 2023-05-23 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_date',
            field=models.DateField(auto_now=True),
        ),
    ]
