# Generated by Django 4.1.4 on 2023-05-24 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_prod_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_image_url',
        ),
    ]
