# Generated by Django 4.1.4 on 2023-05-26 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_product_product_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isInstock',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
