# Generated by Django 4.1.4 on 2023-05-28 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_product_prod_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discription',
            new_name='description',
        ),
    ]
