# Generated by Django 4.1.4 on 2023-05-29 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_product_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='ordering',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
