# Generated by Django 4.1.4 on 2023-05-31 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_category_ordering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='isInstock',
            field=models.PositiveIntegerField(),
        ),
    ]
