# Generated by Django 4.2.3 on 2023-08-11 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_alter_product_isinstock'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlavorCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavorName', models.CharField(max_length=150)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FlavorSubCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavorCategorieName', models.CharField(max_length=150)),
                ('price', models.FloatField(blank=True, null=True)),
                ('flavor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flovarCtg', to='product.flavorcategorie')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
