# Generated by Django 4.2.3 on 2023-08-11 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_flavorcategorie_flavorsubcategorie'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlavorGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavorName', models.CharField(max_length=150)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.RenameField(
            model_name='flavorcategorie',
            old_name='flavorName',
            new_name='flavorCategorieName',
        ),
        migrations.AddField(
            model_name='flavorcategorie',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='FlavorSubCategorie',
        ),
        migrations.AddField(
            model_name='flavorcategorie',
            name='flavor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='flovarCtg', to='product.flavorgroup'),
            preserve_default=False,
        ),
    ]
