# Generated by Django 4.2.3 on 2023-08-11 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_alter_flavorcategorie_flavor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flavorcategorie',
            name='flavor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='product.flavorgroup'),
        ),
    ]
