# Generated by Django 4.1.4 on 2023-07-26 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_cart_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhichList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productId', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
