# Generated by Django 4.2.3 on 2023-08-11 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0015_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
