# Generated by Django 4.2.3 on 2023-08-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0016_cartitem_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='is_eggless',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
