# Generated by Django 4.2.3 on 2023-08-14 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0019_alter_cartitem_is_eggless'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='is_eggless',
            field=models.BooleanField(),
        ),
    ]
