# Generated by Django 4.1.4 on 2023-07-27 05:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0003_rename_alternativeno_userhome_altphoneno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhome',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userhome', to=settings.AUTH_USER_MODEL),
        ),
    ]
