# Generated by Django 4.2.3 on 2023-08-09 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_itemsprice_alter_order_shippingprice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accept', 'Accept'), ('on_delivery', 'On Delivery'), ('delivered', 'Delivered')], default='pending', max_length=50),
        ),
    ]
